# Read the Docs configuration file for Sphinx projects
version: 2

# Build environment configuration
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
    # Optional tools:
    # nodejs: "20"
    # rust: "1.70"
    # golang: "1.20"

# Python dependencies
python:
  install:
    - requirements: docs/requirements.txt

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  builder: "html"          # Default builder
  fail_on_warning: true    # Fail the build if there are warnings

# Optional additional formats
formats:
  - htmlzip
  - pdf
  - epub

# Optional caching (commented out)
# cache:
#   pip: true
#   tools: true
