# Read the Docs configuration file for Sphinx projects
# v2 YAML configuration
# See: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build environment configuration
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
    # Optional tools you might need:
    # nodejs: "20"
    # rust: "1.70"
    # golang: "1.20"

# Python dependencies
python:
  version: "3.12"           # Make sure this matches the 'tools' version above
  install:
    - requirements: docs/requirements.txt

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  builder: "html"            # Default: HTML, can change to 'dirhtml' for simpler URLs
  fail_on_warning: true      # Fail the build if there are warnings (recommended)

# Optional additional build formats
formats:
  - htmlzip
  - pdf
  - epub

# Optionally enable caching to speed up repeated builds
# cache:
#   pip: true
#   tools: true
